### ISSUE TITLE
Build with USD 21.08

### ISSUE THREAD

**Issue by cgarjun** [rodeofx/rdo_replace_resolver#7]
Am trying to build resolver against USD 21.08, I am getting this error, wondering if there is any new method we need to implement to get this working

`usd\21.08-a\include\pxr/usd/ar/defineResolver.h(73): error C2259: 'pxrInternal_v0_21__pxrReserved__::ReplaceResolver': cannot instantiate abstract class
rdo_replace_resolver\0.1.0\build\9d7832ef5bc463433bb407e0dfe3cd10cd35cca0\src\replaceResolver.vcxproj
`

**Comment by jonassorgenfrei** [comment]
Hey @cgarjun  yeah this repo is only implementing the AR1.0. 
But the change to the AR2.0 is not to complicated. 
Check out the defaultResovler at: 
https://github.com/PixarAnimationStudios/USD/tree/release/pxr/usd/ar
And adjusted the content of the functions accrodingly to make it work. 
Most functions are kind of similar and just have an _ in front of it.
